get_user:
    path: '/user/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAdminBundle:User:getUser'
        _api_resource_class: 'Application\AdminBundle\Entity\User'
        _api_item_operation_name: 'getUser'

update_user:
    path: '/user/{id}/'
    methods:  ['PUT']
    defaults:
        _controller: 'ApplicationAdminBundle:User:edit'
        _api_resource_class: 'Application\AdminBundle\Entity\User'
        _api_item_operation_name: 'updateUser'

add_user:
    path: '/users/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAdminBundle:User:add'
        _api_resource_class: 'Application\AdminBundle\Entity\User'
        _api_collection_operation_name: 'addUser'

get_users:
    path: '/users/'
    methods:  ['get']
    defaults:
        _controller: 'ApplicationAdminBundle:User:getUsers'
        _api_resource_class: 'Application\AdminBundle\Entity\User'
        _api_collection_operation_name: 'getUsers'

get_group:
    path: '/group/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAdminBundle:Group:getGroup'
        _api_resource_class: 'Application\AdminBundle\Entity\Group'
        _api_item_operation_name: 'getGroup'

update_group:
    path: '/group/{id}/'
    methods:  ['PUT']
    defaults:
        _controller: 'ApplicationAdminBundle:Group:updateGroup'
        _api_resource_class: 'Application\AdminBundle\Entity\Group'
        _api_item_operation_name: 'updateGroup'

add_group:
    path: '/groups/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAdminBundle:Group:addGroup'
        _api_resource_class: 'Application\AdminBundle\Entity\Group'
        _api_collection_operation_name: 'addGroup'

get_groups:
    path: '/groups/'
    methods:  ['get']
    defaults:
        _controller: 'ApplicationAdminBundle:Group:getGroups'
        _api_resource_class: 'Application\AdminBundle\Entity\Group'
        _api_collection_operation_name: 'getGroups'

login_action:
    path: '/account/login/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAdminBundle:Security:login'
        _api_resource_class: 'Application\AdminBundle\Entity\User'
        _api_collection_operation_name: 'addUser'

register_action:
    path: '/account/register/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAdminBundle:Security:register'

get_profile_action:
    path: '/secured/account/profile/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAdminBundle:Security:getProfile'